---
title: "Exploring the system"
author: "Jeff & Nico"
date: "November 2024"
output:
  pdf_document:
    toc: true
    toc_depth: 5
  html_document:
    theme: flatly
    toc: true
    toc_depth: 5
    number_sections: true
    toc_float:
      collapsed: false
    bookdown: true
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Discussion

$$
H_i^0 \left( \frac{g_i}{m_i} - 1 \right) - S\mu \, \bar{H} = (1 - \mu) H_i
$$

$$
H_i^0 \left( \frac{g_i}{m_i} - 1 \right) = (1 + S\mu - \mu) \, \bar{H}
$$

$$
(1 - \mu) H_i = H_i^0 \left( \frac{g_i}{m_i} - 1 \right) - \frac{\mu}{1 + S\mu - 1} \sum_j H_j^0 \left( \frac{g_j}{m_j} - 1 \right)
$$

Plugging in \( g_i \) on both sides and knowing that \( \text{NPP} = \sum_i g_i H_i \). We get:

$$
(1 - \mu) \, \text{NPP} = \sum_i \left[ m_i H_i^0 \left( \frac{g_i^2}{m_i^2} - \frac{g_i}{m_i} \right) \right] 
- \frac{\mu}{1 + S\mu - 1} \sum_{i,j} \left[ m_i H_i^0 \left( \frac{g_i g_j}{m_i m_j} - \frac{g_i}{m_i} \right) \frac{H_i^0} {H_j^0} \right]
$$

Define:

$$
(\ast) = m_i H_i^0 \left( \frac{g_i^2}{m_i^2} - \frac{g_i}{m_i} \right)
$$


$$
(1 - \mu) \, \text{NPP} = (1 - \frac{\mu}{1 + S\mu - 1}) \sum_i (\ast) - \frac{\mu}{1 + S\mu - 1} \sum_{i,j} m_i H_i^0 \left( \frac{g_i g_j}{m_i m_j} - \frac{g_i}{m_i} \right) \frac{H_j^0} {H_i^0}
$$

Or what is the same:
$$
(1 - \mu) \, \text{NPP} = (1 - \frac{\mu}{1 + S\mu - 1}) \sum_i (\ast) - \frac{\mu}{1 + S\mu - 1} g_i H_i^0 \sum_{i,j} \left( \frac{g_j}{m_j} - 1 \right) \frac{H_j^0} {H_i^0}
$$

## Scenarios
### No competition
$$
\text{NPP} = \sum_i{m_i H_i^0 \left( \frac{g_i^2}{m_i^2} - \frac{g_i}{m_i} \right)}
$$
$$
\text{NPP} = \sum_i{\left(\frac{H_i^0g_i^2}{m_i}-H_i^0g_i\right)}
$$

Since \( \sum_i{p_i} = 1\) and \(\text{NPP}_i = p_i\text{NPP}\):
$$
\text{NPP}_i = \frac{H_i^0g_i^2}{m_i}-H_i^0g_i = H_i^0\left(\frac{g_i^2}{m_i}-g_i\right)
$$

Rearranging into a quadratic equation:

$$
H_i^0 \left( \frac{g_i^2}{m_i} - g_i - \frac{\text{NPP}_i}{H_i^0} \right) = 0.
$$

$$
H_i^0 \left( g_i^2 - m_i g_i - m_i \frac{\text{NPP}_i}{H_i^0} \right) = 0.
$$

Since \( H_i^0 \neq 0 \):

$$
g_i^2 - m_i g_i - m_i \frac{\text{NPP}_i}{H_i^0} = 0.
$$

Since \( g_i > 0 \), we select the positive root:
$$
g_i = \frac{m_i + \sqrt{m_i^2 + \frac{4m_i \, \text{NPP}_i}{H_i^0}}}{2}
$$

To express as \( \frac{g_i}{m_i} \). IMPORTANT! Factor out \(m_i^2\) from the square root
$$
g_i = \frac{m_i + m_i\sqrt{1 + \frac{4 \, \text{NPP}_i}{m_iH_i^0}}}{2}
$$

Hence, since \( \text{NPP}_i = p_i\text{NPP} \) & \( m_i H_i^0 = F_i\):
$$
\frac{g_i}{m_i} = \frac{1 + \sqrt{1 + \frac{4 p_i\text{NPP}}{F_i}}}{2}
$$

If we assume that \(4 p_i\text{NPP} \gg 1\) and then, the condition for \(\frac{g_i}{m_i} > 1 \) is:
$$
p_i \, \text{NPP} > \frac{F_i}{4} 
$$

#### No approximation

But if we don't make the assumption \(4 p_i\text{NPP} \gg 1\), then for \( \frac{g_i}{m_i} \le 1 \):
$$
\frac{1 + \sqrt{1 + \frac{4 p_i\text{NPP}}{F_i}}}{2} \le 1
$$
Which leads to:
$$
\frac{4p_i\,\text{NPP}}{F_i} \le 0
$$
But given that \(p_i \ge 0\) and \(\text{NPP} \ge 0\) and \(F_i \ge 0 \), it's mathematically impossible that \( \frac{g_i}{m_i} \le 1\).

### High \( g_i/m_i \) & No competition

For simplification, we focus on the case where \( g_i \gg m_i \).

$$
(1 - \mu) \, \text{NPP} = (1 - \frac{\mu}{1 + S\mu - 1}) \sum_i{m_i H_i^0 \left( \frac{g_i^2}{m_i^2} \right)} - \frac{\mu}{1 + S\mu - 1} \sum_{i,j} m_i H_i^0 \left( \frac{g_i g_j}{m_i m_j} \right) \frac{H_j^0} {H_i^0}
$$

If no competition (\( \mu = 0 \)), we have:
$$
\text{NPP} = \sum_i{m_i H_i^0 \left( \frac{g_i^2}{m_i^2} \right)}
$$
Since \( \sum_i{p_i} = 1\) and \(\text{NPP}_i = p_i\text{NPP}\):

$$
\text{NPP}_i = m_i H_i^0 \left( \frac{g_i^2}{m_i^2} \right)
$$
$$
\frac{g_i}{m_i} = \sqrt{\frac{\text{NPP}_i}{m_iH_i^0}} = \sqrt{\frac{\text{NPP}_i}{F_i}}
$$
$$
\frac{g_i}{m_i} = \sqrt{\frac{p_i\text{NPP}}{F_i}}
$$
Thus, the condition is \( p_i \text{NPP} > F_i \) where \( F_i = m_i H_i^0 \)









